<?php
function return_message($pwd) {
    $message = "<span style=\"font-family: Calibri, sans-serif; font-size:11pt\">";
    $message .= "<p>Please find below your company's login details to access the <b>Mindset Assessment Profile</b> survey.</p>";
	//$message .= "<p>The same login ID should be used by everybody from your company that wishes to complete the survey.</p>";
    $message .= "<p>The link to the online survey is via <a href='map.meta-lucid.com?c_id=" . $pwd . "'>map.meta-lucid.com?c_id=" . $pwd ."</a></p><br/>";
	//$message .= "<p>The alternative link to the online survey is via <a href='map.meta-lucid.com'>map.meta-lucid.com</a></p>"; 
	//$message .= "<p>The ID is <b>" . $pwd . "</b></p>";
    $message .= "<p>Please inform participants that results will remain confidential and protected by data protection laws.</p>";
	$message .= "<p><i><u>This is an automated email generated by the MAP Server Application, please do not reply to this email</p></u></i><br/>";
    $message .= "<p>Kind regards</p><br/><br/>";
    $message .= "<p><b>MAP Team</b></p>";
    $message .= "<p><b><span style='color:#7bb00f'>Meta-LUCID Ltd</span></b></p>";
    $message .= "<p><img width='418' height='68' alt='ML Logo for email' src='http://map.meta-lucid.com/images/email_logo.png'></img></p>";
    $message .= "<p>e:&nbsp;<u><span style='color:blue'><a target='_blank' href='mailto:info@meta-lucid.com'>info@meta-lucid.com</a></span></u><br/>";
    $message .= "w:&nbsp;<u><span style='color:blue'><target='_blank' href='http:www.meta-lucid.com/'>www.meta-lucid.com</a></span></u></p>";
    $message .= "<p><b><span style='font-size:10.0pt;font-family:Arial, sans-serif;color:#74af27'>UK: Fountain Court, 2 Victoria Square, Victoria Street, St Albans, AL1 3TF</span></b><br/>";
    $message .= "<b><span style='font-size:10.0pt;font-family:Arial, sans-serif;color:#74af27'>US: 5847 San Felipe Street, Suite 1700, Houston, TX 77057</span></b></p>";
    $message .= "<p><span style='font-size:9.0pt;color:#646464'>This email and any attachments may be confidential or legally privileged. If you received this message in error or are not the intended recipient, you should destroy the email message and any attachments or copies, and you are prohibited from retaining, distributing, disclosing or using any information contained herein. Please inform us of the erroneous delivery by return email.</span></p>";
    $message .= "<p><span style='font-size:9.0pt; color:#646464'><br/><br/>Thank you for your cooperation</span></p>";
    $message .= "<p style='margin-left:36.0pt'><span style='font-size:14.0pt;font-fmaily:webdings;color:#76923c'>P </span><span style='font-size:10.0pt;font-family:Tahoma, sans-serif;color:#76923c'>Before printing this email please think about the environment</span></p>";

$message .= "</span>";

return $message;
}